name: Build and Test Server

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          path: pc-landing-page
          submodules: recursive
      - name: Build
        working-directory: pc-landing-page/server
        run: |
          cargo b
      - name: Test
        working-directory: pc-landing-page/server
        run: |
          cargo t
